name: Main pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing modules
        run: npm install
      - name: Building production project
        run: npm run build
      - name: Linting typescript
        run: npm run lint:ts
      - name: Linting styles
        run: npm run lint:scss
      - name: Unit testing
        run: npm run test:unit
      - name: Building storybook
        run: npm run sb:build
      - name: Screenshot testing
        run: npm run test:ui
